#!/usr/bin/env python3
"""
Rewrite `catalogue/known-gaps.json` from what the pipeline actually reports.

WHY THIS EXISTS

The file was hand-maintained, and a hand-maintained record of gaps drifts from the thing it
records. Its own prose said "47 of 942 entries cannot ship" and "zero of them have a romanisation
anywhere in the source, so this is a SOURCE limitation, not a parser bug" — and both claims had
become false. The count was wrong, and the diagnosis was wrong in the most consequential way
possible: thirteen of those entries DID have romanisations on the page, and the parser was
splitting the phrase from the reading wrongly rather than failing to find one.

A gap record that cannot be wrong is worth nothing. So this derives the file from the linter's
own output and refuses to write if the linter is green, because "no gaps" and "the recorder is
broken" look identical from the outside and must not be collapsed into one another.
"""

import json
import re
import subprocess
import sys
from collections import Counter
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
PIPELINE = ROOT / "pipeline"

# Entries the content lint exempts: a sign the traveller READS has no reading to give.
RECOGNITION_EXEMPT = "recognition text whose English is already readable"

BLOCKING = re.compile(r"\(([a-z]{3}-t0-\d+)\): text_romanized is null")


def main():
    proc = subprocess.run(
        ["node", "content/lint.mjs", "../content"],
        cwd=PIPELINE, capture_output=True, text=True, timeout=300,
    )
    out = proc.stdout + proc.stderr

    blocked = []
    for line in out.splitlines():
        if RECOGNITION_EXEMPT in line:
            continue
        m = BLOCKING.search(line)
        if m:
            blocked.append(m.group(1))

    passed = "PASS" in out

    if passed and blocked:
        print("  the linter reported PASS but also blocked entries — refusing to record that")
        return 1
    if passed:
        print("  content lint is PASS: there are no blocking gaps to record.")
        print("  Leaving known-gaps.json alone rather than writing an empty file, because")
        print("  'no gaps' and 'this recorder is broken' are indistinguishable from outside.")
        return 2

    by_lang = Counter(i[:3] for i in blocked)

    # What each blocked entry actually looks like, so the shape can be worked on rather than
    # guessed at. Sampled, not exhaustive — the point is the shape, not the census.
    shapes = []
    for entry_id in sorted(blocked)[:40]:
        code = entry_id[:3]
        path = ROOT / "content" / f"{code}-tier0.jsonl"
        if not path.exists():
            continue
        for line in path.read_text(encoding="utf-8").splitlines():
            if not line.strip():
                continue
            rec = json.loads(line)
            if rec.get("id") == entry_id:
                shapes.append({
                    "id": entry_id,
                    "english": rec.get("text_english"),
                    "native_field": rec.get("text_native"),
                })
                break

    doc = {
        "_comment": [
            "Gaps found by the content linter. GENERATED by pipeline/content/record-gaps.py from",
            "the linter's own output — do not edit by hand, because a hand-maintained record of",
            "gaps drifts from the gaps.",
            "",
            "An entry is blocked when the language's spec declares a non-Latin script and the",
            "entry has no romanisation. That is not the same as the source having none: a phrase",
            "whose transliteration is welded into the phrase field is a PARSER defect, and those",
            "are the ones worth fixing first, because the reading is present on the page.",
        ],
        "blocked_count": len(blocked),
        "by_language": dict(sorted(by_lang.items(), key=lambda kv: -kv[1])),
        "note_on_recognition_text": (
            "Entries exempt from this rule are signs the traveller READS rather than says: "
            "'OPEN', 'TOILET'. Their English is already the phrase, so a romanisation would be "
            "a transliteration of a word they never need to pronounce. Counted separately and "
            "never treated as a gap."
        ),
        "blocked": shapes,
    }
    path = ROOT / "catalogue" / "known-gaps.json"
    path.write_text(json.dumps(doc, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    print(f"  wrote catalogue/known-gaps.json: {len(blocked)} blocked")
    for code, n in sorted(by_lang.items(), key=lambda kv: -kv[1]):
        print(f"    {code}  {n}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
