/**
 * Builds Tier 0 from the spine, for every language.
 *
 * WHAT THIS CHANGES
 *
 * Until now Tier 0 was generated by taking the first N harvested rows per domain, in page order.
 * That produced 1,015 entries across twenty languages with NOTHING in common: 376 distinct English
 * captions, and zero present in all twenty. A traveller who learned "thank you" in Japanese could
 * not find "thank you" in Thai, because nothing tied the two together.
 *
 * Now Tier 0 IS the spine. One slot, one fixed English wording, the same order in every language,
 * filled per language from the phrasebook where it has the row and native-authored Tatoeba where
 * it does not. A language missing a slot reports it as missing rather than substituting whatever
 * happened to be next on a page.
 *
 * THE TRADE, STATED PLAINLY
 *
 * Tier 0 gets smaller: 1,015 entries become roughly 450, about 19-32 per language rather than
 * 30-77. Every language is doing the same job at the same time in the same order, which is the
 * point; a phrasebook where Thai has 77 courtesy phrases and Hindi has 30 unrelated ones is not a
 * smaller problem, it is an incoherent one.
 *
 * NOTHING IS DELETED
 *
 * Harvested rows the spine does not claim are written to `catalogue/tier1-material/<code>.jsonl`.
 * They are Tier 1 material — surplus phrases from the same sources, already harvested and
 * already licensed — waiting on a Tier 1 spine rather than cluttering Tier 0 with things that
 * have no counterpart in the other nineteen languages. Six thousand phrases are not thrown away
 * to tidy a table.
 *
 * THE NINE THIN SLOTS
 *
 * Some slots fill in only one or two languages, because no phrasebook carries them and Tatoeba
 * cannot be searched for them safely. A keyword query matches word overlap rather than meaning:
 * searching "After you" returns Hindi "After cutting the vegetables, put them there" and Japanese
 * "Then simmer 30 minutes and it's done", both native speakers' real sentences and both wrong for
 * the slot. Roughly half the returned sentences do mean the slot; nothing in the pipeline can tell
 * which half without a reader who speaks the language.
 *
 * Those slots are therefore reported as gaps and left empty. Filling them by search would ship
 * about 85 entries whose meaning is wrong and whose provenance looks native, which is the single
 * worst failure mode this project has.
 *
 *     node content/spine-build.mjs              # every language
 *     node content/spine-build.mjs --lang jpn   # one
 *     node content/spine-build.mjs --dry        # report, write nothing
 */

import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'node:fs';
import { createRequire } from 'node:module';
import { join } from 'node:path';
import { assign, loadRowsFor, LATIN_LANGUAGES } from './spine.mjs';

const ROOT = new URL('../..', import.meta.url).pathname;
const SPINE = join(ROOT, 'content', 'spine', 'tier0.json');
const OUT = join(ROOT, 'content');
const MATERIAL = join(ROOT, 'catalogue', 'tier1-material');

const arg = (name, fallback = null) => {
  const i = process.argv.indexOf(name);
  return i >= 0 ? process.argv[i + 1] : fallback;
};
const dry = process.argv.includes('--dry');
const require = createRequire(import.meta.url);
const YAML = require('yaml');

/** The spec's own declared resource names, for the class being used. */
function sourceRefFor(spec, lang, cls, row) {
  const isAttested = cls === 'attested';
  const resources = spec?.resources ?? [];
  // The EVIDENCE CLASS describes the entry; the RESOURCE describes where it came from, and the
  // two are not the same axis. A Tatoeba sentence selected to BE a phrase is `attested` — one
  // person wrote it, it has an id and an author, and both can be checked. The spec declares
  // Tatoeba as `corpus`, which describes the bulk download it was selected from, not this row.
  //
  // Reading the class off the resource instead produced either a missing-resource error or an
  // `corpus` entry in Tier 0, and Tier 0 forbids `corpus`: an aggregate is not one phrase one
  // person wrote, which is the entire distinction the four classes exist to draw.
  // English has no phrasebook and declares no `curated` resource, which is correct rather than an
  // omission: its Tier 0 is authored. So the class is read from the row that filled the slot, not
  // assumed, and a language declaring only `authored` sources without error.
  const res = isAttested
    ? resources.find((r) => /tatoeba/i.test(r.name))
    : resources.find((r) => r.class === cls)
      ?? resources.find((r) => /wikivoyage/i.test(r.name))
      ?? resources.find((r) => /editorial/i.test(r.name));
  // No declared resource means the row cannot be licence-checked, so it cannot ship. The slot is
  // left empty and reported rather than filled: an unattributable entry is not a small gap, it is
  // an entry nobody is permitted to rely on. Not every spec declares Tatoeba — Tamil does not —
  // and this is where that shows up rather than in a linter failure three steps later.
  if (!res) return null;
  return {
    class: cls,
    id: res.name,
    url: res.url ?? null,
    licence: res.licence ?? null,
    // The schema types external_id as a string; Tatoeba ids arrive as integers.
    external_id: isAttested && row.tatoeba_id != null ? String(row.tatoeba_id) : null,
    author: isAttested ? (row.author ?? null) : null,
  };
}

const spine = JSON.parse(readFileSync(SPINE, 'utf8'));
const catalogue = JSON.parse(readFileSync(join(ROOT, 'catalogue', 'languages.json'), 'utf8'));
const only = arg('--lang');

mkdirSync(MATERIAL, { recursive: true });

const report = {};
const globallyMissing = [];
const unsourceable = [];
const duplicates = [];
const unreadable = [];
  const usedNative = new Set();

for (const lang of catalogue.languages) {
  if (only && lang.code !== only) continue;
  const specPath = [join(ROOT, 'specs', `${lang.code}.yaml`), join(ROOT, 'specs', `${lang.name.toLowerCase()}.yaml`)]
    .find((p) => existsSync(p));
  const spec = specPath ? YAML.parse(readFileSync(specPath, 'utf8')) : null;
  const usedNative = new Set();
  const [curated, attested] = loadRowsFor(lang.code);
  const res = assign(spine, curated, attested, LATIN_LANGUAGES.has(lang.code));

  const entries = [];
  let n = 0;
  for (const slot of spine.slots) {
    const row = res.filled.get(slot.id);
    if (!row) { globallyMissing.push([lang.code, slot.id]); continue; }
    const ref = sourceRefFor(spec, lang, row._slot_source ?? 'curated', row);
    if (!ref) {
      unsourceable.push(`${lang.code}/${slot.id} (${row._slot_source})`);
      continue;
    }

    // One phrase may fill one slot. Vietnamese writes "Chào." for both hello and goodbye, and the
    // harvester produced two rows with that text; without this both slots took it and the linter
    // caught the duplicate. The SECOND slot is dropped rather than the first — the earlier slot in
    // spine order is the more common meaning, and order is the spine's whole purpose.
    const native = String(row.native).trim();
    if (usedNative.has(native)) {
      duplicates.push(`${lang.code}/${slot.id} — "${native}" already used`);
      continue;
    }
    usedNative.add(native);

    /**
     * A phrase with no reading, in a language that needs one, cannot ship.
     *
     * Thai `คุณเข้าใจฉันไหม?` ("Do you understand me?") arrived from a phrasebook row carrying no
     * pronunciation, and the Tatoeba fallback carries none either. The content linter refuses it —
     * a Thai entry with no romanisation is unusable for a reader who cannot read Thai — so the slot
     * is left empty here rather than shipped and rejected.
     */
    if (spec?.structure?.script?.primary !== 'Latin' && !row.pronunciation) {
      unreadable.push(`${lang.code}/${slot.id} — no reading for ${spec?.structure?.script?.primary}`);
      continue;
    }
    n += 1;
    const isAttested = row._slot_source === 'attested';
    entries.push({
      id: `${lang.code}-t0-${String(n).padStart(4, '0')}`,
      lang: lang.code,
      tier: 0,
      slot: slot.id,
      domain: slot.domain,
      text_native: row.native,
      text_romanized: row.pronunciation ?? null,
      // The SPINE's wording, not the source page's. This is what makes the tier navigable: the
      // same English sits beside the same meaning in every language. Where the page worded it
      // differently, the page's wording is kept on the record so nothing is silently overwritten.
      text_english: slot.english,
      source_caption: row.english ?? null,
      register: row.register ?? 'neutral',
      direction: slot.direction,
      why: slot.why,
      exchange_id: null,
      exchange_turn: null,
      caution: slot.caution ?? null,
      // The source NAME must be one the spec declares, or the entry cannot be licence-checked
      // and the content linter refuses it. Read from the spec rather than constructed, because
      // the declared name carries the page title — "Wikivoyage: Vietnamese phrasebook" — and a
      // hand-built string is exactly how "Wikivoyage: phrasebook" came to match nothing.
      source: ref,
      failure_flags: [],
    });
  }

  // The surplus is Tier 1 material, not waste.
  const surplus = res.unused.filter((r) => r && r.native && r.english);
  if (!only) {
    writeFileSync(
      join(MATERIAL, `${lang.code}.jsonl`),
      surplus.map((r) => JSON.stringify({
        code: lang.code,
        native: r.native,
        english: r.english,
        pronunciation: r.pronunciation ?? null,
        concept: r.concept ?? null,
        romanized_only: r.romanized_only ?? false,
        // The evidence class and the Tatoeba provenance travel with the row. The first version of
        // this writer emitted only display fields, which made every surplus row look like a
        // phrasebook line and dropped the author and id that CC BY attribution requires — so the
        // Tier 1 material would have been unsourceable for exactly the rows that needed sourcing.
        source_class: r._source ?? 'curated',
        author: r.author ?? null,
        tatoeba_id: r.tatoeba_id ?? null,
        source_page: r.source_page ?? 'Wikivoyage: phrasebook',
        licence: r._source === 'attested' ? 'CC BY 2.0 FR, some CC0' : 'CC BY-SA 4.0',
        source_url: r.url ?? 'https://en.wikivoyage.org/',
      }, null, 0)).join('\n') + (surplus.length ? '\n' : ''),
    );
  }

  report[lang.code] = {
    filled: entries.length,
    slots: spine.slots.length,
    missing: res.missing,
    surplus: surplus.length,
    from_attested: entries.filter((e) => e.source.class === 'attested').length,
  };

  if (!dry) {
    writeFileSync(
      join(OUT, `${lang.code}-tier0.jsonl`),
      entries.map((e) => JSON.stringify(e)).join('\n') + '\n',
    );
  }

  console.log(
    `  ${lang.code.padEnd(4)} ${String(entries.length).padStart(2)}/${spine.slots.length} slots` +
      `   ${report[lang.code].fromAttested ?? report[lang.code].from_attested} attested` +
      `   ${surplus.length} surplus → tier1-material/`,
  );
}

const codes = Object.keys(report).length;
const totalSlots = spine.slots.length * codes;
const filled = Object.values(report).reduce((a, r) => a + r.filled, 0);
console.log(`\n  Tier 0 from the spine: ${filled}/${totalSlots} slots across ${codes} languages`);
console.log(`  surplus held for Tier 1: ${Object.values(report).reduce((a, r) => a + r.surplus, 0)} rows`);

if (duplicates.length || unreadable.length) {
  console.log(`\n  slots held back this build:`);
  for (const d of duplicates) console.log(`    duplicate  ${d}`);
  for (const u of unreadable) console.log(`    no reading ${u}`);
}

if (unsourceable.length) {
  console.log(`\n  ${unsourceable.length} slot(s) held back because their spec declares no matching\n  resource to licence-check against:`);
  for (const u of unsourceable) console.log(`    ${u}`);
}

const thin = new Map();
for (const [code, slot] of globallyMissing) thin.set(slot, (thin.get(slot) ?? 0) + 1);
if (thin.size) {
  console.log(`\n  SLOTS MISSING SOMEWHERE — these cannot be filled safely yet:`);
  for (const [slot, n] of [...thin].sort((a, b) => b[1] - a[1])) {
    const s = spine.slots.find((x) => x.id === slot);
    console.log(`    ${String(n).padStart(2)}/${codes} missing  ${slot.padEnd(26)} "${s.english}"`);
  }
  console.log(`\n  Left empty on purpose. A keyword search for these returns real native sentences`);
  console.log(`  with the wrong meaning — "After you" matches "After cutting the vegetables" — and`);
  console.log(`  nothing but a reader who speaks the language can tell which is which.`);
}

console.log(`\n  -> content/<code>-tier0.jsonl${dry ? ' (dry run, nothing written)' : ''}`);
console.log(`  -> catalogue/tier1-material/<code>.jsonl`);